Repository GRAM-DSM/SharingMyWishlist-iOS, pull requests merged in 2022-08, with the labels that each got.

#12 메인 뷰 추가
  SharingMyWishlist/SharingMyWishlist.xcodeproj/project.pbxproj
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/layer-blue.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/layer-green.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/layer-red.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/layer-white.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/wish-blue.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/wish-green.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/wish-nor.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/wish-red.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Base.lproj/LaunchScreen.storyboard
  SharingMyWishlist/SharingMyWishlist/Header/header.swift
  SharingMyWishlist/SharingMyWishlist/HttpClient/Client.swift
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/AppDelegate.swift
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/LoginViewController.swift
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/SignUpViewController.swift
  SharingMyWishlist/SharingMyWishlist/MainViewController.swift
  SharingMyWishlist/SharingMyWishlist/Model/ListDataModel.swift
  SharingMyWishlist/SharingMyWishlist/SceneDelegate.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/AddListViewController.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/ListTableViewCell.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/MainViewController.swift
Labels: 기능추가, 퍼블리싱

#14 버그 수정
  SharingMyWishlist/SharingMyWishlist/SceneDelegate.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/ListTableViewCell.swift
Labels: 버그수정

#16 완료 & 삭제기능 추가
  SharingMyWishlist/SharingMyWishlist.xcodeproj/project.pbxproj
  SharingMyWishlist/SharingMyWishlist/AppDelegate.swift
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/wish-blu.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Assets.xcassets/wish-gre.colorset/Contents.json
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/LoginViewController.swift
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/SignUpViewController.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/AddListViewController.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/ListTableViewCell.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/MainViewController.swift
Labels: 기능추가

#18 content 비었을때 추가 가능하게 하기
  SharingMyWishlist/SharingMyWishlist.xcodeproj/project.pbxproj
  SharingMyWishlist/SharingMyWishlist/wishListVC/AddListViewController.swift
Labels: 자잘한 수정

#20 새로고침 기능 추가
  SharingMyWishlist/SharingMyWishlist/wishListVC/MainViewController.swift
Labels: 기능추가

#22 로그아웃 기능 추가
  SharingMyWishlist/SharingMyWishlist/wishListVC/MainViewController.swift
Labels: 기능추가

#24 🔀 :: (#23) 리스트 세부사항 추가
  SharingMyWishlist/SharingMyWishlist.xcodeproj/project.pbxproj
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/LoginViewController.swift
  SharingMyWishlist/SharingMyWishlist/Login&SignUpVC/SignUpViewController.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/AddListViewController.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/ListDetailViewController.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/ListTableViewCell.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/MainViewController.swift
Labels: 기능추가

#26 🔀 :: (#25) 모델 형식 리팩토링
  SharingMyWishlist/SharingMyWishlist/Header/header.swift
  SharingMyWishlist/SharingMyWishlist/Model/ListDataModel.swift
  SharingMyWishlist/SharingMyWishlist/wishListVC/MainViewController.swift
Labels: 리펙토링
